### PR TITLE
Propagate active property to tail

### LINKED ISSUE #110: Script does not reset second-level and further patterns on route "back" change
### Description
Created app-location and app-route components:
```
<app-location route="{{route}}"></app-location>
        <app-route
                route="{{route}}"
                pattern="/:section"
                data="{{sectionData}}"
                tail="{{sectionPage}}">
        </app-route>
        <app-route
                route="{{sectionPage}}"
                pattern="/:page"
                data="{{pageData}}"
                tail="{{details}}">
        </app-route>
        <app-route
                route="{{details}}"
                pattern="/:details"
                data="{{detailsData}}">
        </app-route>
```

Added a few buttons:
```
<a href="/company/about"><paper-button>about</paper-button></a>
<a href="/company/services"><paper-button>services</paper-button></a>
<a href="/"><paper-button>home</paper-button></a>
```
Created an observer:
```
observers: [
               '_sectionChanged(route)'
            ],
            _sectionChanged: function (route) {
                console.log(route);
                console.log(this.sectionData);
                console.log(this.pageData);
                //this.index = (!this.pageData || !this.pageData.page);
                //console.log(this.index);
            }
```
### Expected outcome
Click buttons one after another:
```
Object {prefix: "", path: "/company/about", __queryParams: Object}
Object {section: "company"}
Object {page: "about"}
Object {prefix: "", path: "/company/services", __queryParams: Object}
Object {section: "company"}
Object {page: "services"}
Object {prefix: "", path: "/", __queryParams: Object}
Object {section: ""}
undefined
```
### Actual outcome
```
Object {prefix: "", path: "/company/about", __queryParams: Object}
Object {section: "company"}
Object {page: "about"}
Object {prefix: "", path: "/company/services", __queryParams: Object}
Object {section: "company"}
Object {page: "services"}
Object {prefix: "", path: "/", __queryParams: Object}
Object {section: ""}
Object {page: "services"}
```

### Browsers Affected

- [х] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### PR DESCRIPTION
**Pull request by TimvdLippe**
This is an update of #125 to incorporate the feedback of @e111077 and to rebase onto current master. As the repository was moved after I made the original PR, I was unable to push to the original PR.

Supersedes #125 
Fixes #110 
Closes #77

### CODE REVIEW

**Comment by jackdurkalik** [comment]
Any update on this pull request ?

**Comment by RackhamLeNoir** [comment]
For the time being, I use a workaround which is fine in my situation. I used to bind the tail data to an iron-pages and the default was set with fallback-selection="home". So I changed all my links /foo to /foo/home. In this case I always overwrite the previous value. Hope it can help others.

**Comment by vinerz** [comment]
Almost two years later, any news about this?

**Comment by e111077** [comment]
Hello, we considered this when we created app-route, but initially went against doing it largely because of thrashing the databinding system. Thus, the element is working as intended.

We have since put our elements on feature freeze in an effort to lessen our support surface for our understaffed team, and since this element is working as intended, this PR is considered a feature. I have left this PR open as an easy way for users of this element to find this fork.

**Comment by e111077** [comment]
Well it isn't necessarily thrashing, but it would cause the databinding system to fire for an entire subtree of active / inactive elements. App route is already computationally inefficient so we took this definicency into account when creating the element.

**Comment by e111077** [comment]
It should be reliable at the level of the app-route tree that was made inactive which should always be up the tree.

With this interaction model, the view handling that newly-deactivated app-route should be in charge of deactivating the view below it.

**Comment by e111077** [comment]
Perhaps "active" is a bad name for this as it is a declarative representation of a "deactivate" callback

**Comment by mercmobily** [comment]
Well I guess none of this matters anymore since the two-way binding
elements are effectively legacy now...
I guess the routing elements will never make it out of beta now!

**Comment by TimvdLippe** [comment]
This PR is very old and I am no longer pursuing this change. Therefore I am closing this PR.

**Pull request closed without merging**
