### PR TITLE
Fix data and queryParameters not being reset when route becomes inactive

### LINKED ISSUE #206: Property "data" doesn't change when the route isn't active
### Description
app-route.data isn't changed when the route is not active according to the pattern. This results in false positives when only looking at the app-route.data.

### Example
```
    <!-- /523 -->
    <app-route route="{{route}}"
      pattern="/:id"
      data="{{productData}}"
      active="{{productRouteActive}}">
    </app-route>

    <!-- /523/open -->
    <app-route route="{{route}}"
      pattern="/:id/:action"
      data="{{actionData}}"
      active="{{productActionActive}}">
    </app-route>
```
Let's say we have this route, we can add an observer `_observeRoutes(productData, actionData)`. Then check for both of the id's, where we assume that only one can be filled. 

This assumption is false: the not-active route will not have an updated app-route.data, resulting in the false positive of app-route.data.id.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

### PR DESCRIPTION
**Pull request by leolabs**
Should fix #206

### CODE REVIEW

**Comment by leolabs** [comment]
I signed the CLA!

**Comment by Alber70g** [comment]
I think you should change your tabsize to 2 spaces instead of 4

**Comment by NeoLegends** [comment]
Tests are obviously the issue right now, especially since it seems like the expected behavior of the element is to remain how it is if it isn't active. Maybe someone from the polymer elements team can shine some more light on this.

**Comment by bashmish** [comment]
I checked this approach in my setup with three levels of navigation (`/:modelName/:id/:subsection`) and three corresponding `app-route` connected with `tail="subroute"` approach. It didn't work because the moment when `app-route` becomes inactive is different when you expected. Imagine you have such transitions:

1. /my-model/1/subsection => /my-model (user want to see the list of items again)
2. /my-model=> /my-model/1 (use chose this item again)
3. /my-model/1 => /my-model/1/my-subsection (same subsection is open again)

The `app-route` for `/my-model/1/my-subsection` (last in the chain) becomes inactive in the transition 3, but not 1 as you expect. And right afterwards becomes active again. So if you rely in the template on its `routeData`, it will be updated only in transition 3 when it is not needed anymore, because it gets new params (`:id` and `:subsection`) right away as same path is activated :(

**Comment by e111077** [comment]
This was a feature intentionally reverted while in beta because of computational cost. It would propagate down the entire routing subtree upon each change.

Seeing as there has been repeated requests for this feature, I'd be willing to merge a change that hides this feature behind a flag (name I have made up below is crude and I welcome suggestions), so usage would be

```html
<app-route clear-data-on-reset route="{{route}}" data="{{firstDataClearsOnReset}}" tail="{{tail}}">
</app-route>
<app-route clear-data-on-reset route="{{tail}}" data="{{secondDataClearsOnReset}}">
</app-route>
```

**Comment by e111077** [comment]
Closing for now since this has gone stale. Reopen with changes if you wish to go this route

**Comment by jsilvermist** [comment]
I would love this feature, if it has to be a flag, that sounds fine to me!

**Pull request closed without merging**
